# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import coordinateSender_pb2 as proto_dot_coordinateSender__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/coordinateSender_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class coordinateSenderServiceStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLocation = channel.unary_unary(
                '/coordinateSender.coordinateSenderService/SendLocation',
                request_serializer=proto_dot_coordinateSender__pb2.LocationRequest.SerializeToString,
                response_deserializer=proto_dot_coordinateSender__pb2.LocationResponse.FromString,
                _registered_method=True)


class coordinateSenderServiceServicer(object):
    """Define the service
    """

    def SendLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_coordinateSenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocation,
                    request_deserializer=proto_dot_coordinateSender__pb2.LocationRequest.FromString,
                    response_serializer=proto_dot_coordinateSender__pb2.LocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordinateSender.coordinateSenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coordinateSender.coordinateSenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class coordinateSenderService(object):
    """Define the service
    """

    @staticmethod
    def SendLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinateSender.coordinateSenderService/SendLocation',
            proto_dot_coordinateSender__pb2.LocationRequest.SerializeToString,
            proto_dot_coordinateSender__pb2.LocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
